version: '3.7'
services:

  #directly from DockerHub - with particular tag
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - currency-compose-network

  naming-server:
    image: niravvarma/netflix-eureka-naming-server:0.0.1-SNAPSHOT
    #build:
      #context: currency-exchange-service
      #dockerfile: Dockerfile
    ports:
      - "8761:8761"
    restart: always
    networks:
      - currency-compose-network

  #directly from DockerHub - latest one
  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      STORAGE_TYPE: mem
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    ports:
      - "9411:9411"
    depends_on:
      - rabbitmq
    restart: always
    networks:
      - currency-compose-network

  zuul-api-gateway:
    image: niravvarma/netflix-zuul-api-gateway-server:0.0.1-SNAPSHOT
    #build:
      #context: netflix-zuul-api-gateway-server
      #dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    restart: always
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-exchange-service:
    image: niravvarma/currency-exchange-service:0.0.1-SNAPSHOT
    #build:
      #context: currency-exchange-service
      #dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network

  currency-conversion-service:
    image: niravvarma/currency-conversion-service:0.0.1-SNAPSHOT
    #build:
      #context: currency-conversion-service
      #dockerfile: Dockerfile    
    ports:
      - "8100:8100"
    restart: always
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - currency-exchange-service
      - naming-server
      - rabbitmq
      - zipkin-server
    networks:
      - currency-compose-network
  
# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network: